version: "3.9"
services:
    db:
        image: postgres:9.6
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - bundle:/bundle
            - .:/dwt-sample
        ports:
            - "3000:3000"
        depends_on:
            - db

volumes:
    bundle: